// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Main_Screen_screen_init(void)
{
    ui_Main_Screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_Screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_buttonTest = lv_btn_create(ui_Main_Screen);
    lv_obj_set_width(ui_buttonTest, 282);
    lv_obj_set_height(ui_buttonTest, 50);
    lv_obj_set_x(ui_buttonTest, -227);
    lv_obj_set_y(ui_buttonTest, 166);
    lv_obj_set_align(ui_buttonTest, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonTest, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_buttonTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonTest, lv_color_hex(0x64A966), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_buttonTest, lv_color_hex(0x0C4224), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_buttonTestLabel = lv_label_create(ui_buttonTest);
    lv_obj_set_width(ui_buttonTestLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_buttonTestLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_buttonTestLabel, -5);
    lv_obj_set_y(ui_buttonTestLabel, 0);
    lv_obj_set_align(ui_buttonTestLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_buttonTestLabel, "Press Me");
    lv_obj_set_style_text_font(ui_buttonTestLabel, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelGreenShoeGarage = lv_label_create(ui_Main_Screen);
    lv_obj_set_width(ui_labelGreenShoeGarage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_labelGreenShoeGarage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelGreenShoeGarage, 126);
    lv_obj_set_y(ui_labelGreenShoeGarage, -194);
    lv_obj_set_align(ui_labelGreenShoeGarage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelGreenShoeGarage, "Green Shoe Garage v1.0");
    lv_obj_set_style_text_font(ui_labelGreenShoeGarage, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar2 = lv_bar_create(ui_Main_Screen);
    lv_bar_set_range(ui_Bar2, 0, 1024);
    lv_bar_set_value(ui_Bar2, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar2, 572);
    lv_obj_set_height(ui_Bar2, 73);
    lv_obj_set_x(ui_Bar2, -14);
    lv_obj_set_y(ui_Bar2, -32);
    lv_obj_set_align(ui_Bar2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0xEAE0E0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar2, lv_color_hex(0x115606), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_buttonTest, ui_event_buttonTest, LV_EVENT_ALL, NULL);
    uic_buttonTest = ui_buttonTest;

}
